### ISSUE TITLE
3D SVG for FTO only shows six faces

### ISSUE THREAD

**Issue by rokicki** [cubing/cubing.js#124]
Go to twizzle explorer; select FTO in the puzzles drop-down, then open options, ensure 3D is selected, and then select SVG from the actions drop-down.  The resulting SVG only renders six of the eight faces (the other two are perpendicular to the viewer).  A different default orientation should be selected for this.  Other puzzles may also be affected.

A simpler way to reproduce is to just run

    node dist/bin/puzzle-geometry-bin.js --svg --3d FTO > t.svg ; open -a Safari.app t.svg

The 2D SVG is fine.

**Comment by lgarron** [comment]
It's so cute!

<img width="1275" alt="Screen Shot 2021-07-22 at 20 43 19" src="https://user-images.githubusercontent.com/248078/126735133-5e556b0a-4240-4589-bf10-8a1d6661321a.png">

Personally, I think reusing the vertex-centered views instead of a net might be nice. R and BR could even be joined at the edge to form a distorted net.

<img width="845" alt="Screen Shot 2021-07-22 at 20 44 08" src="https://user-images.githubusercontent.com/248078/126735172-a71a5d7c-3243-43cf-9c8e-251c54b2c9e9.png">
