### ISSUE TITLE
Redefine options for `experimentalAppendMove`

### ISSUE THREAD

**Issue by anicolao** [cubing/cubing.js#207]
This is an enhancement/API change request. Since `experimentalAppendMove` is labeled "experimental", I am assuming that comments and changes to its API are still welcome and that we can have a discussion and change it. If that's not possible, just let me know and I will discard these ideas.

Philosophically, I think options the user passes in `options` should be orthogonal and interoperable. The specific set of options I personally require are `sliceMoves`, `wideMoves`, `mod`, and a subset of `coalesce`. Currently `mod` is a sub-option of `coalesce` and `coalesce` does too much work.

I propose that there should be no option whose effect depends on another option being enabled -- that is, that `mod` should stand alone, and not be an option that only has an effect if `coalesce` is true. I would have the following options:

`coalesce`: combine successive turns _in the same direction only_ into a single turn.
e.g. R + R2 = R3 but R + R2' = R + R2'

`cancel`: cancel successive turns against prior moves of the same face
e.g. R + R2' = R'

`sliceMoves`: combine basic face moves plus rotation moves to recognize slices
e.g. L' R x = M'

`wideMoves`: combine basic face moves plus rotation moves to recognize wide moves
e.g. L x = r

`mod`: apply modulus to the last move after any effect from the above moves
e.g. mod 4: L2 L = L'

My goal is to have a timer for roux solvers that produces correct results. For someone executing a roux solve on a bluetooth cube, the right options would be `coalesce`, `sliceMoves`, and `wideMoves`; but the other functionality here would all produce a wrong solve analysis/movecount and should not be used. As the code currently is, `coalesce` does the wrong thing for me, so I can't only add slices and wide moves; minimally I need something that corresponds to my proposed new semantics for `coalesce`.

If we can't change `coalesce`'s meaning at this stage because of other dependencies, I propose that I add a `merge` option that behaves the way I want (only coalesce moves in the same direction, with no modulus fixes).

**Comment by lgarron** [comment]
Thanks! I think your breakdown works well. My thoughts:

- Ideally we can make this compatible with [arguments to `Alg.simplify()`](https://github.com/cubing/cubing.js/blob/5a15e5ac925894e3f197636286736a465ec5f1b9/src/cubing/alg/traversal.ts#L131-L135).
- I'm very concerned about short names that could have different meanings to different people. To be as unambiguous as possible, one option `coalesceSameDirection` and `cancelOppositeDirection`. But:
- I think it would also make sense to have a structured argument specifically for coalescing. And I think the name `collapse` from `SimplifyOptions` might actually be the most intuitive. So, something like:

```ts
type CollapseOptions = {
  sameDirection?: boolean;
  oppositeDirection?: boolean;
  wideMoves?: boolean;
  sliceMoves?: boolean;
  quantumMoveOrder?: (quantumMove: QuantumMove) => number;
}

experimentalAppendMove(
  alg: Alg,
  newMove: Move,
  options?: {
    collapse?: CollapseOptions
  },
);

Alg.simplify({
  collapse: CollapseOptions;
  depth?: number | null;
})
```

Depending on how ergonomic this is in practice, it might also be worth supporting `type CollapseOptions = boolean | {...}` where `true` means a default subset of options.

I'm a little concerned that `wideMoves` and `sliceMoves` could have conflicting interpretations of algs, e.g. should `M' R2` be rewritten to `r R`? The other way around? What if there's another `L` somewhere in there? But I don't think it's a huge problem, because we're certainly not promising any deterministic behaviour when we label something as "experimental", and we also don't have to promise stable heuristics until we're ready.

**Comment by anicolao** [comment]
For `wideMoves` and `sliceMoves` my intent was only combinations of what I called "basic face moves" with rotations to be transformed, so M' and r wouldn't be candidates for transforming (as they're not in ULFRDB families).

I am not sure how to apply the `CollapseOptions` proposal without essentially promoting these into the 'real' API as well as the experimental one. And if we're to modify Alg.simplify() to take new options, I'd be in favour of eliminating the experimental entry point at the same time. 

Perhaps as an intermediate step I can put up a version with `ExperimentalCollapseOptions` for the experimental entry point, leave `Alg.simplify` alone, and we can see what that looks like?

**Comment by lgarron** [comment]
> For `wideMoves` and `sliceMoves` my intent was only combinations of what I called "basic face moves" with rotations to be transformed, so M' and r wouldn't be candidates for transforming (as they're not in ULFRDB families).

Ah, that sounds like a good idea.

> Perhaps as an intermediate step I can put up a version with `ExperimentalCollapseOptions` for the experimental entry point, leave `Alg.simplify` alone, and we can see what that looks like?

Yeah, that sounds reasonable. I wouldn't be too afraid to touch `simplify` or change back `simplify` to `experimentalSimplify` though.

**Comment by anicolao** [comment]
OK this first step is in https://github.com/cubing/cubing.js/pull/211

Once we agree on what to do with the element/URL parameters, I will finish off this PR and hope to commit it.

**Comment by anicolao** [comment]
I'd like to close off / clean up any cruft I have left behind, so I am going to close this as a dead end.
