### ISSUE TITLE
[cubing.js issue] Square-1 rendering issue in Brave?

### ISSUE THREAD

**Issue by GhostShadow0316** [cubing/cubing.js#299]
### Steps to reproduce the issue

I'm trying to make a Square-1 scramble display

### Observed behaviour

It doesn't work

### 🖼 Screenshots

https://codepen.io/ghostshadow0316/pen/GRzoEBY

### Expected behaviour

No Error

### Environment

on brave browser

### Additional info

other puzzles works fine

**Comment by lgarron** [comment]
Could you let us know more about the device you're testing on, as well as any screenshots or console logs that might show what's happening?

I'm seeing on issues in Brave on macOS.

**Comment by GhostShadow0316** [comment]
the console logs nothing
and my device is brave on Window10

**Comment by lgarron** [comment]
I just tested Brave on Windows and it's displaying just fine.

It occurs to me that you might be trying to say that the display is showing a solved puzzle instead of a scrambled puzzle.

For the scramble in your example, you'll have to make sure there are spaces around the `/` moves: `(4, 0) / (6, 0) / (5, 5) / (0, -3) / (-3, -3) / (-2, 0) / (-3, -3) / (-1, 0) / (-4, 0) / (0, -4) / (-5, 0) / (0, -2) / (0, -5)`

**Comment by GhostShadow0316** [comment]
thank you very much
that is what I mean! sorry for my poor english
I test it and it works!
