### ISSUE TITLE
Parser Libraries missing in 10.3 build

### ISSUE THREAD

**Issue by lukas681** [cubing/cubing.js#62]
Hello,
I am not sure,  whether my setup is just somehow wrong, but I tried to import the library via npm i to my vue project. Version 10.3 from npm

I get the error that the "parser" library export could not be found and looking in the filesystem confirms me that these files are missing. Reinstalling them let me reproduce the issue.
Is is just some weird setting on my side, or are the libraries missing?

**Comment by lukas681** [comment]
Closed, after 10th retry, files where successfully fetched ...

**Comment by lukas681** [comment]
I found out that the parser libraries are not included in ./dist/ fetched by npm, but in ./src/.
A workaround is to manually copy the files from src to dist after npm install.

It seems also that the export for OrientationEvent is somehow corrupt.

Could you confirm that they are missing there and maybe add them.

BTW: Nice work in reverse engineering the GAN cube state!!!

**Comment by lgarron** [comment]
Could you specify more about how you are using the library, e.g. reproduction steps, expected behaviour, and what you observer?

None of the main exported libraries should be referencing the `src` folder (only the definitions for `app` files, which are currently included but shouldn't affect things).

> It seems also that the export for OrientationEvent is somehow corrupt.

Could you also specify what you're trying to do? We currently don't export it at all, since it's essentially used as an interface – I don't see anything I would describe as "corrupt". But if you're using TypeScript, I can see why you might want it.

**Comment by lgarron** [comment]
@lukas681 ping :-D
